In [2]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
array_1d = np.array([10, 20, 30])

# Add the 1D array to each row of the 2D array
result = array_2d + array_1d
print("Broadcasting result:\n", result)

Broadcasting result:
 [[11 22 33]
 [14 25 36]]


In [3]:
# Advance indexing technique

# Create an array of random numbers
random_array = np.random.randint(1, 100, size=(5, 5))
print("Random array:\n", random_array)

# Boolean indexing to find elements greater than 50
filtered_array = random_array[random_array > 50]
print("Elements greater than 50:\n", filtered_array)

Random array:
 [[64 94 88 72 34]
 [45 95 17 42 57]
 [91 99 54 35 14]
 [52 82 47 41 87]
 [34 30 91 20 24]]
Elements greater than 50:
 [64 94 88 72 95 57 91 99 54 52 82 87 91]


In [5]:
# Fancy indexing
# Using fancy indexing to get specific rows
array_2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = [0, 2]
fancy_indexed_array = array_2d[row_indices]
print("Fancy indexed array:\n", fancy_indexed_array)

Fancy indexed array:
 [[10 20 30]
 [70 80 90]]


In [6]:
import numpy as np

# Create two NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Perform element-wise operations
sum_ab = a + b          # Addition
diff_ab = a - b         # Subtraction
prod_ab = a * b         # Multiplication
div_ab = a / b          # Division

print("Sum:", sum_ab)
print("Difference:", diff_ab)
print("Product:", prod_ab)
print("Division:", div_ab)

Sum: [5 7 9]
Difference: [-3 -3 -3]
Product: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [7]:
# Adding a scalar to an array
c = a + 2
print("Array after adding scalar:", c)

Array after adding scalar: [3 4 5]


In [8]:
# Create a random array
data = np.array([10, 20, 30, 40, 50])

# Calculate aggregates
total = np.sum(data)
average = np.mean(data)
minimum = np.min(data)
maximum = np.max(data)
std_deviation = np.std(data)

print("Total:", total)
print("Average:", average)
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Standard Deviation:", std_deviation)

Total: 150
Average: 30.0
Minimum: 10
Maximum: 50
Standard Deviation: 14.142135623730951


In [ ]:
# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])

sum_of_columns = np.sum(matrix, axis=0)  # Sum across columns
sum_of_rows = np.sum(matrix, axis=1)  # Sum across rows

print("Sum of columns:", sum_of_columns)
print("Sum of rows:", sum_of_rows)

Sum of columns: [5 7 9]
Sum of rows: [ 6 15]


In [13]:
#Boolean indexing example
# Create an array of random numbers
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Get all values greater than 5
filtered_data = data[data > 5]
print("Values greater than 5:", filtered_data)

# Replace values based on a condition
new_data = np.where(data > 5, 1, 0)  # 1 if value > 5, else 0
print("New data with conditions applied:", new_data)

Values greater than 5: [ 6  7  8  9 10]
New data with conditions applied: [0 0 0 0 0 1 1 1 1 1]


In [14]:
# Create an array of angles (in radians)
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

# Compute sine and cosine
sine_values = np.sin(angles)
cosine_values = np.cos(angles)

print("Sine values:", sine_values)
print("Cosine values:", cosine_values)

Sine values: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]
Cosine values: [ 1.0000000e+00  6.1232340e-17 -1.0000000e+00 -1.8369702e-16]


In [15]:
# Create an array
values = np.array([1, 2, 3])

# Compute exponential and logarithm
exp_values = np.exp(values)
log_values = np.log(values)

print("Exponential values:", exp_values)
print("Logarithmic values:", log_values)

Exponential values: [ 2.71828183  7.3890561  20.08553692]
Logarithmic values: [0.         0.69314718 1.09861229]


In [16]:
# Create two matrices
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Calculate the dot product
dot_product = np.dot(matrix_a, matrix_b)
print("Dot Product:\n", dot_product)

Dot Product:
 [[19 22]
 [43 50]]
